version: '3.7'

services:
  paper:
    build: .
    container_name: psychics-abilities
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./.docker:/data
    entrypoint:
      - /docker-setup-plugin
      - https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.10/Kotlin.jar
      - https://github.com/noonmaru/inv-fx/releases/download/1.3.0/InvFX.jar
      - https://github.com/noonmaru/psychics/releases/download/0.9.3/Psychics.jar
      - https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar
